Update master_myportfoliapp.yml

diff --git a/.github/workflows/master_myportfoliapp.yml b/.github/workflows/master_myportfoliapp.yml
--- a/.github/workflows/master_myportfoliapp.yml
+++ b/.github/workflows/master_myportfoliapp.yml
@@ -1,6 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy Node.js app to Azure Web App - MyPortfoliApp
 
 on:
@@ -19,14 +16,17 @@ jobs:
       - name: Set up Node.js version
         uses: actions/setup-node@v3
         with:
-          node-version: '18.x'
+          node-version: '14.x'  # Adjust Node.js version here
 
-      - name: npm install, build, and test
-        run: |
-          npm install
-          npm run build --if-present
-          npm run test --if-present
-      
+      - name: npm install
+        run: npm install
+
+      - name: npm run build
+        run: npm run build --if-present
+
+      - name: npm run test
+        run: npm run test --if-present || echo "Tests failed"
+
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v3
         with:
@@ -39,15 +39,13 @@ jobs:
     environment:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
-    permissions:
-      id-token: write #This is required for requesting the JWT
 
     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v3
         with:
           name: node-app
-      
+
       - name: Login to Azure
         uses: azure/login@v1
         with:
@@ -62,4 +60,3 @@ jobs:
           app-name: 'MyPortfoliApp'
           slot-name: 'Production'
           package: .
-          
